# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXhVRzYkv2EM5USoMgTM5n2IOdkaG8Cp
"""

pip install streamlit pandas matplotlib

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ======================
# KONFIGURASI HALAMAN
# ======================
st.set_page_config(
    page_title="E-Commerce Dashboard",
    layout="wide"
)

st.title("📊 E-Commerce Dashboard")
st.markdown(
    "Dashboard ini menyajikan hasil analisis tren penjualan dan "
    "segmentasi pelanggan berdasarkan RFM Analysis."
)

# ======================
# LOAD DATA
# ======================
@st.cache_data
def load_data():
    return pd.read_csv("Dashboard/main_data.csv")

df = load_data()

# --- Prepare 'order_month' column ---
df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["order_month"] = df["order_purchase_timestamp"].dt.to_period("M").astype(str)
# ======================
# PREVIEW DATA
# ======================
with st.expander("Lihat Data"):
    st.dataframe(df.head())

# ======================
# TREN PENJUALAN BULANAN
# ======================
st.subheader("📈 Tren Penjualan Bulanan")

monthly_sales = (
    df.groupby("order_month")["revenue"]
      .sum()
      .reset_index()
)

fig1, ax1 = plt.subplots(figsize=(10, 4))
ax1.plot(monthly_sales["order_month"], monthly_sales["revenue"], marker='o')
ax1.set_xlabel("Bulan")
ax1.set_ylabel("Total Revenue")
ax1.set_title("Tren Penjualan Bulanan")
plt.xticks(rotation=45)

st.pyplot(fig1)

# ======================
# SEGMENTASI PELANGGAN
# ======================
st.subheader("👥 Segmentasi Pelanggan (RFM)")

segment_count = df["Segment"].value_counts().reset_index()
segment_count.columns = ["Segment", "Jumlah"]

fig2, ax2 = plt.subplots(figsize=(6, 4))
ax2.bar(segment_count["Segment"], segment_count["Jumlah"])
ax2.set_xlabel("Segmen")
ax2.set_ylabel("Jumlah Transaksi")
ax2.set_title("Distribusi Segmen Pelanggan")

st.pyplot(fig2)

# ======================
# INSIGHT SINGKAT
# ======================
st.markdown("""
### 📌 Insight Utama
- Penjualan menunjukkan fluktuasi dari waktu ke waktu dengan periode tertentu
  mengalami peningkatan.
- Mayoritas pelanggan berada pada segmen *Loyal Customer*.
- Segmen *Champion* memiliki jumlah lebih sedikit namun bernilai tinggi.
""")
